### ISSUE TITLE
Native notifications are blocking the app

### ISSUE THREAD

**Issue by khaitbek** [smart-office-uz/desktop-app#3]
## Current behavior
Whenever I get a new notification, I can't do anything with the app. I have to close the notification in order to be able to interact with the app. 

## Expected behavior
Notifications should not prevent me from interacting with the app

**Comment by khaitbek** [comment]
I confirm that this happened to me on Arch Linux. But I am not sure if it is the case on Windows/Mac

**Comment by ikholmatov** [comment]
are you answering to yourself?

**Comment by ikholmatov** [comment]
What is this program for?

**Comment by khaitbek** [comment]
> What is this program for?

It is a desktop app for [Smart Office](https://smart-office.uz) written in Tauri

**Comment by khaitbek** [comment]
> are you answering to yourself?

I setted up a webhook that automatically sends a message to Telegram, so I was just testing it up. And also, I was note taking

**Comment by khaitbek** [comment]
https://github.com/hoodie/notify-rust/commit/346167f0e8531d3c2454feca1c0c4deb0e834592

This looks like a fix, but I am not sure. Will take a look at it for sure

**Comment by khaitbek** [comment]
Fixed by using show_async() instead of show() in notify-rust

https://docs.rs/notify-rust/4.11.3/notify_rust/struct.Notification.html#method.show_async
